name: ReturnEnchant
version: '${version}'
main: org.MAGd.returnenchant.Returnenchant
api-version: '1.21'
description: Remove enchantments from items and return them as enchanted books
softdepend: [ExcellentEnchants]
commands:
  returnenchant:
    description: Remove enchantments from the item in your hand and return them as enchanted books
    usage: /<command>
    permission: returnenchant.use
permissions:
  returnenchant.use:
    description: Allows players to use the returnenchant command
    default: false
